const martyrsOfKarbala = [
    "Imam Hussain ibn Ali",
    "Ali Akbar ibn Hussain",
    "Ali Asghar ibn Hussain",
    "Abbas ibn Ali",
    "Qasim ibn Hasan",
    "Ali Zainul Abideen",
    "Muhammad ibn Ali",
    "Ja'far ibn Ali ",
    "Aun ibn Abdullah",
    "Muhammad ibn Abdullah ",
    "Abdullah ibn Muslim ibn Aqeel",
    "Qasim ibn Hassan",
    "Jaun ibn Huwairith",
    "Amr ibn Qart al-Zubai",
    "Habib ibn Mazahir al-Asadi",
    "Wahab ibn Abdullah Kalbi",
    "Qarib ibn Abi Abdullah",
    "Uthman ibn Abdillah",
    "Saeed ibn Abdullah Hanafi",
    "Nafe ibn Hilal al-Jamali",
    "Hajjaj ibn Masruq al-Abdi",
    "Saif ibn Abdullah al-Hashimi",
    "Ubaidullah ibn Abbas al-Mazini",
    "Abis ibn Abi Shabeeb al-Shakiri",
    "Abdullah ibn Abbas al-Hilali",
    "Amr ibn Qareez al-Tamimi",
    "Muslim ibn Ausajah al-Asadi",
    "Muslim ibn Abdullah ibn Umar al-Kalbi",
    "Qais ibn Musahar al-Saidawi",
    "Alqamah ibn Qais al-Tamimi",
    "Burair ibn Khudair al-Hamadani",
    "Malik ibn Dinar al-Juhani",
    "Zuhair ibn Qain al-Bajali",
    "Zaid ibn Ribab al-Shakiri",
    "Qais ibn Mashir al-Saidawi",
    "Abdur Rahman ibn Aqil al-Tamimi",
    "Muslim ibn Awsaja al-Asadi",
    "Bashir ibn Amr al-Kalbi",
    "Bashir ibn Ghaziyyah al-Kinani",
    "Mas'ood ibn Amr al-Juhani",
    "Juhaym ibn Tariq al-Abdi",
    "Abdullah ibn Zaid al-Ansari",
    "Habib ibn Muzahir al-Asadi",
    "Hurr ibn Yazid al-Riyahi",
    "Aqeel ibn Abi Talib",
    "Zuhayr ibn Qain al-Bajali",
    "Zuhayr ibn Muhammad al-Tamimi",
    "Mas'ood ibn Hajjaj al-Abdi",
    "Sa'id ibn Abdullah Hanafi",
    "Humayd ibn Muslim al-Azdi",
    "Habib ibn Muzahir al-Asadi",
    "Uthman ibn Maz'un al-Jahni",
    "Mus'ab ibn Amr al-Thaqafi",
    "Ishaq ibn Abdullah al-Kindi",
    "Jundab ibn Abdullah al-Azdi",
    "Ghurayb ibn Qais al-Sa'di",
    "Uthman ibn Qareez al-Tamimi",
    "Jareer ibn Abdullah al-Bajali",
    "Ma'ruf ibn Khudair al-Jamali",
    "Muslim ibn Ausaja al-Asadi",
    "Hani ibn Thabit al-Harithi",
    "Abdullah ibn Qasim al-Hadrami",
    "Umar ibn Qasim al-Hadrami",
    "Abdullah ibn Hasan",
    "Bishr ibn Amr al-Kinani",
    "Umar ibn Muslim al-Asadi",
    "Abdullah ibn Umayr al-Laithi",
    "Amr ibn Khalid al-Juhani",
    "Atiyyah ibn Saad al-Kindi",
    "Yazid ibn Harith al-Muharibi",
    "Qasim ibn Amr al-Sa'di",
    "Hani ibn Urwah al-Tamimi"
  ];



  export default martyrsOfKarbala;